[2022-11-23T06:28:09.464+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:28:09.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:28:09.493+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:09.492+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:28:09.544+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:09.540+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:28:09.545+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:28:09.633+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.176 seconds
[2022-11-23T06:28:39.900+0000] {processor.py:154} INFO - Started process (PID=97) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:28:39.901+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:28:39.904+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:39.904+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:28:39.924+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:28:39.921+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:28:39.925+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:28:39.958+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.066 seconds
[2022-11-23T06:29:10.007+0000] {processor.py:154} INFO - Started process (PID=161) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:29:10.008+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:29:10.009+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:10.009+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:29:10.019+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:10.018+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:29:10.020+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:29:10.048+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.045 seconds
[2022-11-23T06:29:40.980+0000] {processor.py:154} INFO - Started process (PID=218) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:29:40.982+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:29:40.983+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:40.983+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:29:40.995+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:29:40.992+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:29:40.995+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:29:41.016+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.042 seconds
[2022-11-23T06:30:11.449+0000] {processor.py:154} INFO - Started process (PID=281) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:30:11.451+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:30:11.452+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:11.452+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:30:11.466+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:11.465+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:30:11.467+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:30:11.491+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.046 seconds
[2022-11-23T06:30:42.124+0000] {processor.py:154} INFO - Started process (PID=335) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:30:42.124+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:30:42.125+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:42.125+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:30:42.134+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:30:42.133+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:30:42.135+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:30:42.156+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.035 seconds
[2022-11-23T06:31:12.691+0000] {processor.py:154} INFO - Started process (PID=402) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:31:12.692+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:31:12.693+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:12.693+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:31:12.706+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:12.704+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:31:12.707+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:31:12.728+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.042 seconds
[2022-11-23T06:31:43.455+0000] {processor.py:154} INFO - Started process (PID=459) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:31:43.456+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:31:43.457+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:43.457+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:31:43.468+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:31:43.467+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:31:43.468+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:31:43.488+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.035 seconds
[2022-11-23T06:32:14.269+0000] {processor.py:154} INFO - Started process (PID=523) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:32:14.271+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:32:14.273+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:14.272+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:32:14.284+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:14.282+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:32:14.284+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:32:14.317+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.056 seconds
[2022-11-23T06:32:45.347+0000] {processor.py:154} INFO - Started process (PID=588) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:32:45.348+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:32:45.348+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:45.348+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:32:45.356+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:32:45.355+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:32:45.356+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:32:45.376+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.033 seconds
[2022-11-23T06:33:16.071+0000] {processor.py:154} INFO - Started process (PID=645) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:33:16.074+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:33:16.075+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:16.075+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:33:16.084+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:16.083+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:33:16.084+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:33:16.111+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.044 seconds
[2022-11-23T06:33:46.725+0000] {processor.py:154} INFO - Started process (PID=709) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:33:46.727+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:33:46.729+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:46.728+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:33:46.739+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:33:46.738+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:33:46.739+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:33:46.761+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.044 seconds
[2022-11-23T06:34:16.962+0000] {processor.py:154} INFO - Started process (PID=766) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:34:16.964+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:34:16.971+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:16.970+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:34:16.987+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:16.984+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:34:16.988+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:34:17.016+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.060 seconds
[2022-11-23T06:34:47.628+0000] {processor.py:154} INFO - Started process (PID=833) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:34:47.633+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:34:47.634+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:47.634+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:34:47.642+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:34:47.641+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:34:47.643+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:34:47.662+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.040 seconds
[2022-11-23T06:35:17.976+0000] {processor.py:154} INFO - Started process (PID=896) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:35:17.977+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:35:17.978+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:17.978+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:35:17.988+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:17.987+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:35:17.989+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:35:18.016+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.046 seconds
[2022-11-23T06:35:48.410+0000] {processor.py:154} INFO - Started process (PID=953) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:35:48.411+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:35:48.412+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:48.412+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:35:48.420+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:35:48.419+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:35:48.421+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:35:48.443+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.038 seconds
[2022-11-23T06:36:19.064+0000] {processor.py:154} INFO - Started process (PID=1021) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:36:19.067+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:36:19.068+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:19.068+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:36:19.076+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:19.075+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:36:19.076+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:36:19.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.035 seconds
[2022-11-23T06:36:49.841+0000] {processor.py:154} INFO - Started process (PID=1079) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:36:49.843+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:36:49.845+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:49.844+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:36:49.857+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:36:49.856+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:36:49.857+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:36:49.877+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.042 seconds
[2022-11-23T06:37:20.864+0000] {processor.py:154} INFO - Started process (PID=1143) to work on /opt/airflow/dags/validator.py
[2022-11-23T06:37:20.865+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T06:37:20.866+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:37:20.866+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T06:37:20.874+0000] {logging_mixin.py:137} INFO - [2022-11-23T06:37:20.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T06:37:20.875+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T06:37:20.893+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.031 seconds
[2022-11-23T08:45:02.975+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:45:02.977+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:45:02.979+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:02.978+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:45:03.017+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:03.013+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:45:03.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:45:03.136+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.173 seconds
[2022-11-23T08:45:33.229+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:45:33.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:45:33.232+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:33.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:45:33.244+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:45:33.242+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:45:33.244+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:45:33.265+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.043 seconds
[2022-11-23T08:46:03.304+0000] {processor.py:154} INFO - Started process (PID=154) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:46:03.305+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:46:03.306+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:03.306+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:46:03.322+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:03.321+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:46:03.322+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:46:03.347+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.046 seconds
[2022-11-23T08:46:34.260+0000] {processor.py:154} INFO - Started process (PID=220) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:46:34.261+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:46:34.263+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:34.263+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:46:34.277+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:46:34.276+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:46:34.278+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:46:34.295+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.044 seconds
[2022-11-23T08:47:05.114+0000] {processor.py:154} INFO - Started process (PID=277) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:47:05.116+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:47:05.117+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:05.117+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:47:05.130+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:05.129+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:47:05.130+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:47:05.147+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.040 seconds
[2022-11-23T08:47:35.381+0000] {processor.py:154} INFO - Started process (PID=344) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:47:35.383+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:47:35.384+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:35.384+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:47:35.398+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:47:35.397+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:47:35.398+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:47:35.424+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.047 seconds
[2022-11-23T08:48:05.485+0000] {processor.py:154} INFO - Started process (PID=400) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:48:05.486+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:48:05.487+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:05.487+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:48:05.494+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:05.493+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:48:05.494+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:48:05.511+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.029 seconds
[2022-11-23T08:48:35.742+0000] {processor.py:154} INFO - Started process (PID=464) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:48:35.743+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:48:35.744+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:35.744+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:48:35.753+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:48:35.752+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:48:35.754+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:48:35.776+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.037 seconds
[2022-11-23T08:49:06.445+0000] {processor.py:154} INFO - Started process (PID=520) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:49:06.452+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:49:06.453+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:06.453+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:49:06.468+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:06.467+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:49:06.469+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:49:06.535+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.094 seconds
[2022-11-23T08:49:36.735+0000] {processor.py:154} INFO - Started process (PID=575) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:49:36.736+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:49:36.737+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:36.737+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:49:36.749+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:49:36.748+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:49:36.749+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:49:36.774+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.043 seconds
[2022-11-23T08:50:18.652+0000] {processor.py:154} INFO - Started process (PID=623) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:50:18.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:50:18.654+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:18.654+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:50:18.666+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:18.663+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:50:18.667+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:50:18.720+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.074 seconds
[2022-11-23T08:50:49.508+0000] {processor.py:154} INFO - Started process (PID=679) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:50:49.514+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:50:49.515+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:49.514+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:50:49.538+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:50:49.537+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:50:49.539+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:50:49.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.070 seconds
[2022-11-23T08:51:20.620+0000] {processor.py:154} INFO - Started process (PID=735) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:51:20.621+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:51:20.622+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:20.622+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:51:20.632+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:20.631+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:51:20.633+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:51:20.676+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.060 seconds
[2022-11-23T08:51:50.834+0000] {processor.py:154} INFO - Started process (PID=796) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:51:50.857+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:51:50.858+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:50.858+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:51:50.900+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:50.899+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T08:51:50.901+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:51:51.019+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.200 seconds
[2022-11-23T08:51:51.536+0000] {processor.py:154} INFO - Started process (PID=800) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:51:51.549+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:51:51.572+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:51.571+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:51:51.630+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:51:51.629+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:51:51.631+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:51:51.700+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.168 seconds
[2022-11-23T08:52:22.639+0000] {processor.py:154} INFO - Started process (PID=853) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:52:22.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:52:22.650+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:22.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:52:22.667+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:22.665+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:52:22.668+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:52:22.734+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.113 seconds
[2022-11-23T08:52:53.054+0000] {processor.py:154} INFO - Started process (PID=906) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:52:53.058+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:52:53.059+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:53.059+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:52:53.077+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:52:53.076+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:52:53.077+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:52:53.140+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.090 seconds
[2022-11-23T08:53:23.246+0000] {processor.py:154} INFO - Started process (PID=961) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:53:23.248+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:53:23.248+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:23.248+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:53:23.257+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:23.256+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:53:23.257+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:53:23.279+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.037 seconds
[2022-11-23T08:53:53.889+0000] {processor.py:154} INFO - Started process (PID=1026) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:53:53.890+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:53:53.891+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:53.891+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:53:53.900+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:53:53.899+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:53:53.900+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:53:53.932+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.047 seconds
[2022-11-23T08:54:24.020+0000] {processor.py:154} INFO - Started process (PID=1077) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:54:24.021+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:54:24.022+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:24.022+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:54:24.031+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:24.030+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:54:24.031+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:54:24.056+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.041 seconds
[2022-11-23T08:54:54.499+0000] {processor.py:154} INFO - Started process (PID=1133) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:54:54.500+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:54:54.501+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:54.500+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:54:54.510+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:54:54.509+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:54:54.511+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:54:54.535+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.044 seconds
[2022-11-23T08:55:25.141+0000] {processor.py:154} INFO - Started process (PID=1197) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:55:25.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:55:25.143+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:55:25.143+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:55:25.158+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:55:25.157+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:55:25.159+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:55:25.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.096 seconds
[2022-11-23T08:55:56.069+0000] {processor.py:154} INFO - Started process (PID=1253) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:55:56.070+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:55:56.071+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:55:56.071+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:55:56.080+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:55:56.079+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:55:56.081+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:55:56.105+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.040 seconds
[2022-11-23T08:56:26.835+0000] {processor.py:154} INFO - Started process (PID=1318) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:56:26.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:56:26.849+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:26.849+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:56:26.892+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:26.866+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:56:26.892+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:56:27.024+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.197 seconds
[2022-11-23T08:56:57.076+0000] {processor.py:154} INFO - Started process (PID=1374) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:56:57.077+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:56:57.078+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:57.078+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:56:57.086+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:56:57.085+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:56:57.086+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:56:57.107+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.034 seconds
[2022-11-23T08:57:27.431+0000] {processor.py:154} INFO - Started process (PID=1437) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:57:27.433+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:57:27.434+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:27.434+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:57:27.453+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:27.452+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:57:27.454+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:57:27.529+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.102 seconds
[2022-11-23T08:57:57.710+0000] {processor.py:154} INFO - Started process (PID=1494) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:57:57.734+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:57:57.735+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:57.735+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:57:57.762+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:57:57.760+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:57:57.763+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:57:57.920+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.215 seconds
[2022-11-23T08:58:28.647+0000] {processor.py:154} INFO - Started process (PID=1548) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:58:28.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:58:28.655+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:28.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:58:28.688+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:28.681+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:58:28.689+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:58:28.736+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.113 seconds
[2022-11-23T08:58:59.245+0000] {processor.py:154} INFO - Started process (PID=1603) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:58:59.268+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:58:59.270+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:59.269+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:58:59.364+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:58:59.332+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:58:59.365+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:58:59.402+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.182 seconds
[2022-11-23T08:59:29.812+0000] {processor.py:154} INFO - Started process (PID=1656) to work on /opt/airflow/dags/validator.py
[2022-11-23T08:59:29.814+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T08:59:29.830+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:59:29.830+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T08:59:29.883+0000] {logging_mixin.py:137} INFO - [2022-11-23T08:59:29.870+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T08:59:29.883+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T08:59:30.002+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.243 seconds
[2022-11-23T09:00:00.717+0000] {processor.py:154} INFO - Started process (PID=1713) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:00:00.720+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:00:00.721+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:00.721+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:00:00.755+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:00.753+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:00:00.755+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:00:00.933+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.223 seconds
[2022-11-23T09:00:31.486+0000] {processor.py:154} INFO - Started process (PID=1769) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:00:31.488+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:00:31.489+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:31.489+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:00:31.500+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:00:31.498+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:00:31.501+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:00:31.530+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.049 seconds
[2022-11-23T09:01:01.718+0000] {processor.py:154} INFO - Started process (PID=1823) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:01:01.719+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:01:01.720+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:01.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:01:01.731+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:01.730+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:01:01.732+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:01:01.755+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.041 seconds
[2022-11-23T09:01:32.191+0000] {processor.py:154} INFO - Started process (PID=1889) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:01:32.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:01:32.193+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:32.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:01:32.206+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:01:32.204+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:01:32.207+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:01:32.236+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.049 seconds
[2022-11-23T09:02:02.460+0000] {processor.py:154} INFO - Started process (PID=1945) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:02:02.464+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:02:02.465+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:02.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:02:02.484+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:02.482+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:02:02.484+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:02:02.546+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.091 seconds
[2022-11-23T09:02:32.655+0000] {processor.py:154} INFO - Started process (PID=2008) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:02:32.656+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:02:32.658+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:32.657+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:02:32.698+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:02:32.688+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:02:32.699+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:02:32.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.121 seconds
[2022-11-23T09:03:03.236+0000] {processor.py:154} INFO - Started process (PID=2067) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:03:03.237+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:03:03.238+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:03.238+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:03:03.269+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:03.267+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from airflow_omniparser.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-23T09:03:03.270+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:03:03.373+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.147 seconds
[2022-11-23T09:03:17.885+0000] {processor.py:154} INFO - Started process (PID=2107) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:03:17.887+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:03:17.889+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:17.888+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:03:17.912+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:17.904+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:03:17.913+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:03:17.988+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.115 seconds
[2022-11-23T09:03:48.690+0000] {processor.py:154} INFO - Started process (PID=2163) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:03:48.693+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:03:48.694+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:48.694+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:03:48.714+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:03:48.713+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:03:48.715+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:03:48.785+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.100 seconds
[2022-11-23T09:04:19.385+0000] {processor.py:154} INFO - Started process (PID=2218) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:04:19.386+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:04:19.387+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:19.387+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:04:19.398+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:19.397+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:04:19.398+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:04:19.421+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.039 seconds
[2022-11-23T09:04:50.231+0000] {processor.py:154} INFO - Started process (PID=2282) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:04:50.237+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:04:50.238+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:50.238+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:04:50.275+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:04:50.269+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:04:50.276+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:04:50.339+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.112 seconds
[2022-11-23T09:05:20.643+0000] {processor.py:154} INFO - Started process (PID=2339) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:05:20.668+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:05:20.670+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:20.669+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:05:20.719+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:20.714+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:05:20.740+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:05:20.791+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.154 seconds
[2022-11-23T09:05:50.904+0000] {processor.py:154} INFO - Started process (PID=2395) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:05:50.912+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:05:50.913+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:50.913+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:05:50.943+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:05:50.934+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:05:50.944+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:05:51.018+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.120 seconds
[2022-11-23T09:06:21.658+0000] {processor.py:154} INFO - Started process (PID=2451) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:06:21.660+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:06:21.661+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:21.661+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:06:21.672+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:21.670+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:06:21.672+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:06:21.701+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.047 seconds
[2022-11-23T09:06:51.890+0000] {processor.py:154} INFO - Started process (PID=2509) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:06:51.891+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:06:51.893+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:51.892+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:06:51.903+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:06:51.902+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:06:51.904+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:06:51.946+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.061 seconds
[2022-11-23T09:07:22.348+0000] {processor.py:154} INFO - Started process (PID=2571) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:07:22.349+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:07:22.350+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:22.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:07:22.394+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:22.392+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:07:22.394+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:07:22.515+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.172 seconds
[2022-11-23T09:07:52.677+0000] {processor.py:154} INFO - Started process (PID=2628) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:07:52.679+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:07:52.680+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:52.679+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:07:52.690+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:07:52.689+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:07:52.691+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:07:52.716+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.043 seconds
[2022-11-23T09:08:23.563+0000] {processor.py:154} INFO - Started process (PID=2684) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:08:23.564+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:08:23.565+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:23.565+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:08:23.577+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:23.575+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-23T09:08:23.577+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:08:23.608+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.050 seconds
[2022-11-23T09:08:54.400+0000] {processor.py:154} INFO - Started process (PID=2749) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:08:54.404+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:08:54.405+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:54.405+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:08:54.417+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:08:54.416+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:08:54.417+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:08:54.448+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.053 seconds
[2022-11-23T09:09:24.481+0000] {processor.py:154} INFO - Started process (PID=2805) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:09:24.482+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:09:24.483+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:24.483+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:09:24.492+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:24.491+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:09:24.492+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:09:24.511+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.033 seconds
[2022-11-23T09:09:55.408+0000] {processor.py:154} INFO - Started process (PID=2869) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:09:55.415+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:09:55.420+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:55.420+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:09:55.485+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:09:55.480+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:09:55.485+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:09:55.536+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.150 seconds
[2022-11-23T09:10:26.109+0000] {processor.py:154} INFO - Started process (PID=2925) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:10:26.110+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:10:26.111+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:26.111+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:10:26.121+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:26.120+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:10:26.122+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:10:26.148+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.043 seconds
[2022-11-23T09:10:56.647+0000] {processor.py:154} INFO - Started process (PID=2990) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:10:56.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:10:56.650+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:56.649+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:10:56.668+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:10:56.667+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:10:56.669+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:10:56.703+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.061 seconds
[2022-11-23T09:11:27.054+0000] {processor.py:154} INFO - Started process (PID=3046) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:11:27.061+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:11:27.062+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:27.062+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:11:27.101+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:27.099+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:11:27.102+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:11:27.215+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.165 seconds
[2022-11-23T09:11:57.877+0000] {processor.py:154} INFO - Started process (PID=3110) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:11:57.878+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:11:57.879+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:57.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:11:57.886+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:11:57.885+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:11:57.886+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:11:57.912+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.038 seconds
[2022-11-23T09:12:28.586+0000] {processor.py:154} INFO - Started process (PID=3165) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:12:28.587+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:12:28.588+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:28.588+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:12:28.614+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:28.612+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:12:28.614+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:12:28.644+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.070 seconds
[2022-11-23T09:12:59.536+0000] {processor.py:154} INFO - Started process (PID=3229) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:12:59.537+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:12:59.538+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:59.538+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:12:59.551+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:12:59.550+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:12:59.552+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:12:59.588+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.056 seconds
[2022-11-23T09:13:29.657+0000] {processor.py:154} INFO - Started process (PID=3284) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:13:29.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:13:29.659+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:29.659+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:13:29.671+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:29.669+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:13:29.671+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:13:29.699+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.047 seconds
[2022-11-23T09:13:59.832+0000] {processor.py:154} INFO - Started process (PID=3346) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:13:59.835+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:13:59.837+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:59.836+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:13:59.855+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:13:59.854+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:13:59.856+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:13:59.942+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.115 seconds
[2022-11-23T09:14:30.007+0000] {processor.py:154} INFO - Started process (PID=3399) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:14:30.008+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:14:30.010+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:14:30.009+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:14:30.028+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:14:30.027+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:14:30.029+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:14:30.061+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.066 seconds
[2022-11-23T09:15:00.971+0000] {processor.py:154} INFO - Started process (PID=3455) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:15:00.973+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:15:00.974+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:00.974+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:15:00.984+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:00.983+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:15:00.985+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:15:01.027+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.060 seconds
[2022-11-23T09:15:31.823+0000] {processor.py:154} INFO - Started process (PID=3520) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:15:31.827+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:15:31.828+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:31.828+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:15:31.838+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:15:31.837+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:15:31.839+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:15:31.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.051 seconds
[2022-11-23T09:16:01.952+0000] {processor.py:154} INFO - Started process (PID=3577) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:16:01.953+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:16:01.954+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:16:01.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:16:01.964+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:16:01.963+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:16:01.964+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:16:01.990+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.042 seconds
[2022-11-23T09:16:32.201+0000] {processor.py:154} INFO - Started process (PID=3642) to work on /opt/airflow/dags/validator.py
[2022-11-23T09:16:32.204+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T09:16:32.206+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:16:32.205+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T09:16:32.222+0000] {logging_mixin.py:137} INFO - [2022-11-23T09:16:32.220+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T09:16:32.222+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T09:16:32.252+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.068 seconds
[2022-11-23T11:05:26.430+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/validator.py
[2022-11-23T11:05:26.441+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T11:05:26.442+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:26.441+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T11:05:26.465+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:26.461+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T11:05:26.467+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T11:05:26.539+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.113 seconds
[2022-11-23T11:05:56.774+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/validator.py
[2022-11-23T11:05:56.776+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T11:05:56.777+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:56.777+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T11:05:56.786+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:05:56.785+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T11:05:56.787+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T11:05:56.805+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.035 seconds
[2022-11-23T11:06:27.494+0000] {processor.py:154} INFO - Started process (PID=155) to work on /opt/airflow/dags/validator.py
[2022-11-23T11:06:27.495+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T11:06:27.497+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:27.496+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T11:06:27.520+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:27.517+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T11:06:27.520+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T11:06:27.567+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.078 seconds
[2022-11-23T11:06:58.057+0000] {processor.py:154} INFO - Started process (PID=220) to work on /opt/airflow/dags/validator.py
[2022-11-23T11:06:58.059+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T11:06:58.060+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:58.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T11:06:58.090+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:06:58.087+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T11:06:58.091+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T11:06:58.122+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.070 seconds
[2022-11-23T11:07:28.920+0000] {processor.py:154} INFO - Started process (PID=275) to work on /opt/airflow/dags/validator.py
[2022-11-23T11:07:28.921+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T11:07:28.925+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:07:28.924+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T11:07:28.936+0000] {logging_mixin.py:137} INFO - [2022-11-23T11:07:28.935+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T11:07:28.937+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T11:07:28.957+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.043 seconds
[2022-11-23T12:41:40.102+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/validator.py
[2022-11-23T12:41:40.104+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T12:41:40.105+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:41:40.104+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T12:41:40.122+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:41:40.118+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T12:41:40.124+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T12:41:40.163+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.065 seconds
[2022-11-23T12:42:10.197+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/validator.py
[2022-11-23T12:42:10.198+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T12:42:10.199+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:10.199+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T12:42:10.205+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:10.205+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T12:42:10.206+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T12:42:10.224+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.030 seconds
[2022-11-23T12:42:40.321+0000] {processor.py:154} INFO - Started process (PID=155) to work on /opt/airflow/dags/validator.py
[2022-11-23T12:42:40.323+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T12:42:40.323+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:40.323+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T12:42:40.331+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:42:40.331+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T12:42:40.332+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T12:42:40.353+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.034 seconds
[2022-11-23T12:43:10.834+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/validator.py
[2022-11-23T12:43:10.838+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T12:43:10.838+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:10.838+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T12:43:10.846+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:10.845+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T12:43:10.846+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T12:43:10.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.034 seconds
[2022-11-23T12:43:41.728+0000] {processor.py:154} INFO - Started process (PID=286) to work on /opt/airflow/dags/validator.py
[2022-11-23T12:43:41.730+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-23T12:43:41.731+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:41.731+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-23T12:43:41.742+0000] {logging_mixin.py:137} INFO - [2022-11-23T12:43:41.741+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 4, in <module>
    from omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'omniParser'
[2022-11-23T12:43:41.742+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-23T12:43:41.760+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.040 seconds
