[2022-11-18 06:50:42,328] {processor.py:163} INFO - Started process (PID=45) to work on /opt/airflow/dags/validator.py
[2022-11-18 06:50:42,386] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 06:50:42,444] {logging_mixin.py:109} INFO - [2022-11-18 06:50:42,426] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 06:50:44,656] {logging_mixin.py:109} INFO - [2022-11-18 06:50:44,652] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 8, in <module>
    from hl7_data_pipeline.hl7 import HL7Message
ModuleNotFoundError: No module named 'hl7_data_pipeline'
[2022-11-18 06:50:44,694] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 06:50:44,724] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 2.443 seconds
[2022-11-18 06:51:37,811] {processor.py:163} INFO - Started process (PID=81) to work on /opt/airflow/dags/validator.py
[2022-11-18 06:51:37,842] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 06:51:37,849] {logging_mixin.py:109} INFO - [2022-11-18 06:51:37,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 06:51:39,387] {logging_mixin.py:109} INFO - [2022-11-18 06:51:39,386] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 8, in <module>
    from hl7_data_pipeline.hl7 import HL7Message
ModuleNotFoundError: No module named 'hl7_data_pipeline'
[2022-11-18 06:51:39,490] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 06:51:39,564] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 1.797 seconds
[2022-11-18 11:03:17,492] {processor.py:163} INFO - Started process (PID=46) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:03:17,495] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:03:17,538] {logging_mixin.py:109} INFO - [2022-11-18 11:03:17,538] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:03:20,018] {logging_mixin.py:109} INFO - [2022-11-18 11:03:20,013] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from hl7_data_pipeline.hl7 import HL7Message
ModuleNotFoundError: No module named 'hl7_data_pipeline'
[2022-11-18 11:03:20,051] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:03:20,083] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 2.630 seconds
[2022-11-18 11:11:16,256] {processor.py:163} INFO - Started process (PID=44) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:11:16,258] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:11:16,259] {logging_mixin.py:109} INFO - [2022-11-18 11:11:16,259] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:11:18,444] {logging_mixin.py:109} INFO - [2022-11-18 11:11:18,423] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from hl7_data_pipeline.hl7 import HL7Message
ModuleNotFoundError: No module named 'hl7_data_pipeline'
[2022-11-18 11:11:18,538] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:11:18,592] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 2.362 seconds
[2022-11-18 11:13:30,368] {processor.py:163} INFO - Started process (PID=195) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:13:30,371] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:13:30,373] {logging_mixin.py:109} INFO - [2022-11-18 11:13:30,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:13:30,530] {logging_mixin.py:109} INFO - [2022-11-18 11:13:30,529] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from hl7_data_pipeline.hl7 import HL7Message
ModuleNotFoundError: No module named 'hl7_data_pipeline'
[2022-11-18 11:13:30,579] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:13:30,601] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.239 seconds
[2022-11-18 11:13:49,621] {processor.py:163} INFO - Started process (PID=240) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:13:49,625] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:13:49,636] {logging_mixin.py:109} INFO - [2022-11-18 11:13:49,636] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:13:50,350] {logging_mixin.py:109} INFO - [2022-11-18 11:13:50,343] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:13:50,461] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:13:50,526] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.924 seconds
[2022-11-18 11:14:20,928] {processor.py:163} INFO - Started process (PID=293) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:14:20,930] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:14:20,931] {logging_mixin.py:109} INFO - [2022-11-18 11:14:20,931] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:14:21,179] {logging_mixin.py:109} INFO - [2022-11-18 11:14:21,176] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:14:21,223] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:14:21,238] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.316 seconds
[2022-11-18 11:14:51,291] {processor.py:163} INFO - Started process (PID=346) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:14:51,297] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:14:51,298] {logging_mixin.py:109} INFO - [2022-11-18 11:14:51,298] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:14:51,433] {logging_mixin.py:109} INFO - [2022-11-18 11:14:51,432] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:14:51,450] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:14:51,460] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.172 seconds
[2022-11-18 11:15:21,538] {processor.py:163} INFO - Started process (PID=399) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:15:21,548] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:15:21,550] {logging_mixin.py:109} INFO - [2022-11-18 11:15:21,549] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:15:21,815] {logging_mixin.py:109} INFO - [2022-11-18 11:15:21,814] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:15:21,839] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:15:21,852] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.317 seconds
[2022-11-18 11:15:52,709] {processor.py:163} INFO - Started process (PID=450) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:15:52,719] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:15:52,720] {logging_mixin.py:109} INFO - [2022-11-18 11:15:52,720] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:15:53,287] {logging_mixin.py:109} INFO - [2022-11-18 11:15:53,278] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:15:53,344] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:15:53,363] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.658 seconds
[2022-11-18 11:16:24,224] {processor.py:163} INFO - Started process (PID=496) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:16:24,231] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:16:24,232] {logging_mixin.py:109} INFO - [2022-11-18 11:16:24,231] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:16:24,580] {logging_mixin.py:109} INFO - [2022-11-18 11:16:24,572] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:16:24,620] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:16:24,638] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.420 seconds
[2022-11-18 11:16:55,220] {processor.py:163} INFO - Started process (PID=558) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:16:55,230] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:16:55,231] {logging_mixin.py:109} INFO - [2022-11-18 11:16:55,231] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:16:55,498] {logging_mixin.py:109} INFO - [2022-11-18 11:16:55,497] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:16:55,520] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:16:55,529] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.314 seconds
[2022-11-18 11:17:25,674] {processor.py:163} INFO - Started process (PID=602) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:17:25,677] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:17:25,678] {logging_mixin.py:109} INFO - [2022-11-18 11:17:25,678] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:17:25,992] {logging_mixin.py:109} INFO - [2022-11-18 11:17:25,987] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:17:26,024] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:17:26,043] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.377 seconds
[2022-11-18 11:17:56,192] {processor.py:163} INFO - Started process (PID=655) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:17:56,194] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:17:56,196] {logging_mixin.py:109} INFO - [2022-11-18 11:17:56,196] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:17:56,452] {logging_mixin.py:109} INFO - [2022-11-18 11:17:56,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:17:56,473] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:17:56,500] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.315 seconds
[2022-11-18 11:18:26,822] {processor.py:163} INFO - Started process (PID=716) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:18:26,824] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:18:26,825] {logging_mixin.py:109} INFO - [2022-11-18 11:18:26,825] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:18:27,141] {logging_mixin.py:109} INFO - [2022-11-18 11:18:27,136] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:18:27,164] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:18:27,190] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.371 seconds
[2022-11-18 11:18:57,693] {processor.py:163} INFO - Started process (PID=769) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:18:57,700] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:18:57,702] {logging_mixin.py:109} INFO - [2022-11-18 11:18:57,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:18:57,963] {logging_mixin.py:109} INFO - [2022-11-18 11:18:57,962] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:18:58,001] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:18:58,023] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.344 seconds
[2022-11-18 11:19:28,208] {processor.py:163} INFO - Started process (PID=823) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:19:28,210] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:19:28,211] {logging_mixin.py:109} INFO - [2022-11-18 11:19:28,211] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:19:28,428] {logging_mixin.py:109} INFO - [2022-11-18 11:19:28,426] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:19:28,448] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:19:28,465] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.262 seconds
[2022-11-18 11:19:58,655] {processor.py:163} INFO - Started process (PID=875) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:19:58,657] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:19:58,658] {logging_mixin.py:109} INFO - [2022-11-18 11:19:58,658] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:19:58,937] {logging_mixin.py:109} INFO - [2022-11-18 11:19:58,935] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:19:58,962] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:19:58,975] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.325 seconds
[2022-11-18 11:20:29,017] {processor.py:163} INFO - Started process (PID=927) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:20:29,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:20:29,020] {logging_mixin.py:109} INFO - [2022-11-18 11:20:29,020] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:20:29,220] {logging_mixin.py:109} INFO - [2022-11-18 11:20:29,218] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:20:29,238] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:20:29,248] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.237 seconds
[2022-11-18 11:20:59,315] {processor.py:163} INFO - Started process (PID=981) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:20:59,324] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:20:59,325] {logging_mixin.py:109} INFO - [2022-11-18 11:20:59,325] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:20:59,631] {logging_mixin.py:109} INFO - [2022-11-18 11:20:59,628] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:20:59,684] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:20:59,715] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.411 seconds
[2022-11-18 11:21:30,061] {processor.py:163} INFO - Started process (PID=1034) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:21:30,063] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:21:30,069] {logging_mixin.py:109} INFO - [2022-11-18 11:21:30,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:21:30,608] {logging_mixin.py:109} INFO - [2022-11-18 11:21:30,605] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:21:30,663] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:21:30,676] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.642 seconds
[2022-11-18 11:23:10,974] {processor.py:163} INFO - Started process (PID=37) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:23:10,980] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:23:10,988] {logging_mixin.py:109} INFO - [2022-11-18 11:23:10,988] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:23:11,497] {logging_mixin.py:109} INFO - [2022-11-18 11:23:11,478] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:23:11,542] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:23:11,561] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.600 seconds
[2022-11-18 11:23:42,033] {processor.py:163} INFO - Started process (PID=89) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:23:42,037] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:23:42,039] {logging_mixin.py:109} INFO - [2022-11-18 11:23:42,039] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:23:42,155] {logging_mixin.py:109} INFO - [2022-11-18 11:23:42,154] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:23:42,179] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:23:42,192] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.163 seconds
[2022-11-18 11:24:13,035] {processor.py:163} INFO - Started process (PID=142) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:24:13,044] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:24:13,045] {logging_mixin.py:109} INFO - [2022-11-18 11:24:13,045] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:24:13,309] {logging_mixin.py:109} INFO - [2022-11-18 11:24:13,305] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:24:13,369] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:24:13,410] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.378 seconds
[2022-11-18 11:24:43,600] {processor.py:163} INFO - Started process (PID=196) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:24:43,611] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:24:43,623] {logging_mixin.py:109} INFO - [2022-11-18 11:24:43,623] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:24:44,017] {logging_mixin.py:109} INFO - [2022-11-18 11:24:44,016] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:24:44,049] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:24:44,070] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.474 seconds
[2022-11-18 11:25:14,142] {processor.py:163} INFO - Started process (PID=249) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:25:14,144] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:25:14,145] {logging_mixin.py:109} INFO - [2022-11-18 11:25:14,145] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:25:14,247] {logging_mixin.py:109} INFO - [2022-11-18 11:25:14,246] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:25:14,262] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:25:14,270] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.133 seconds
[2022-11-18 11:25:44,963] {processor.py:163} INFO - Started process (PID=302) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:25:44,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:25:44,965] {logging_mixin.py:109} INFO - [2022-11-18 11:25:44,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:25:45,078] {logging_mixin.py:109} INFO - [2022-11-18 11:25:45,077] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:25:45,102] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:25:45,113] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.154 seconds
[2022-11-18 11:26:15,173] {processor.py:163} INFO - Started process (PID=356) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:26:15,174] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:26:15,175] {logging_mixin.py:109} INFO - [2022-11-18 11:26:15,175] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:26:15,468] {logging_mixin.py:109} INFO - [2022-11-18 11:26:15,460] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:26:15,508] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:26:15,528] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.363 seconds
[2022-11-18 11:26:45,828] {processor.py:163} INFO - Started process (PID=408) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:26:45,830] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:26:45,837] {logging_mixin.py:109} INFO - [2022-11-18 11:26:45,836] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:26:46,060] {logging_mixin.py:109} INFO - [2022-11-18 11:26:46,059] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:26:46,104] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:26:46,125] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.301 seconds
[2022-11-18 11:27:16,528] {processor.py:163} INFO - Started process (PID=459) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:27:16,531] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:27:16,533] {logging_mixin.py:109} INFO - [2022-11-18 11:27:16,532] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:27:16,650] {logging_mixin.py:109} INFO - [2022-11-18 11:27:16,649] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:27:16,668] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:27:16,681] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.164 seconds
[2022-11-18 11:27:46,749] {processor.py:163} INFO - Started process (PID=511) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:27:46,751] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:27:46,752] {logging_mixin.py:109} INFO - [2022-11-18 11:27:46,752] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:27:47,086] {logging_mixin.py:109} INFO - [2022-11-18 11:27:47,080] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:27:47,109] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:27:47,126] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.387 seconds
[2022-11-18 11:28:17,380] {processor.py:163} INFO - Started process (PID=565) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:28:17,393] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:28:17,394] {logging_mixin.py:109} INFO - [2022-11-18 11:28:17,394] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:28:17,749] {logging_mixin.py:109} INFO - [2022-11-18 11:28:17,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:28:17,783] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:28:17,800] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.426 seconds
[2022-11-18 11:28:47,926] {processor.py:163} INFO - Started process (PID=621) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:28:47,928] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:28:47,929] {logging_mixin.py:109} INFO - [2022-11-18 11:28:47,929] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:28:48,110] {logging_mixin.py:109} INFO - [2022-11-18 11:28:48,108] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:28:48,134] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:28:48,148] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.227 seconds
[2022-11-18 11:29:18,540] {processor.py:163} INFO - Started process (PID=672) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:29:18,547] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:29:18,558] {logging_mixin.py:109} INFO - [2022-11-18 11:29:18,558] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:29:19,273] {logging_mixin.py:109} INFO - [2022-11-18 11:29:19,257] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:29:19,344] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:29:19,444] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.973 seconds
[2022-11-18 11:29:50,581] {processor.py:163} INFO - Started process (PID=725) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:29:50,583] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:29:50,587] {logging_mixin.py:109} INFO - [2022-11-18 11:29:50,587] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:29:50,907] {logging_mixin.py:109} INFO - [2022-11-18 11:29:50,904] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:29:50,946] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:29:50,967] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.399 seconds
[2022-11-18 11:30:21,044] {processor.py:163} INFO - Started process (PID=779) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:30:21,047] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:30:21,048] {logging_mixin.py:109} INFO - [2022-11-18 11:30:21,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:30:21,385] {logging_mixin.py:109} INFO - [2022-11-18 11:30:21,376] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:30:21,435] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:30:21,458] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.420 seconds
[2022-11-18 11:30:46,352] {processor.py:163} INFO - Started process (PID=815) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:30:46,358] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:30:46,360] {logging_mixin.py:109} INFO - [2022-11-18 11:30:46,360] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:30:46,622] {logging_mixin.py:109} INFO - [2022-11-18 11:30:46,616] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:30:46,683] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:30:46,701] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.357 seconds
[2022-11-18 11:31:16,960] {processor.py:163} INFO - Started process (PID=869) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:31:16,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:31:16,974] {logging_mixin.py:109} INFO - [2022-11-18 11:31:16,974] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:31:17,203] {logging_mixin.py:109} INFO - [2022-11-18 11:31:17,194] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:31:17,237] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:31:17,254] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.302 seconds
[2022-11-18 11:31:47,387] {processor.py:163} INFO - Started process (PID=922) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:31:47,389] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:31:47,390] {logging_mixin.py:109} INFO - [2022-11-18 11:31:47,390] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:31:47,566] {logging_mixin.py:109} INFO - [2022-11-18 11:31:47,565] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:31:47,590] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:31:47,603] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.222 seconds
[2022-11-18 11:32:18,680] {processor.py:163} INFO - Started process (PID=972) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:32:18,681] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:32:18,693] {logging_mixin.py:109} INFO - [2022-11-18 11:32:18,693] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:32:19,540] {logging_mixin.py:109} INFO - [2022-11-18 11:32:19,536] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 5, in <module>
    from airflow.providers.amazon.aws.hooks.s3 import S3Hook
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:32:19,598] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:32:19,618] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.970 seconds
[2022-11-18 11:32:21,794] {processor.py:163} INFO - Started process (PID=975) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:32:21,801] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:32:21,824] {logging_mixin.py:109} INFO - [2022-11-18 11:32:21,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:32:22,414] {logging_mixin.py:109} INFO - [2022-11-18 11:32:22,413] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 11:32:22,453] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:32:22,466] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.695 seconds
[2022-11-18 11:32:52,751] {processor.py:163} INFO - Started process (PID=1019) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:32:52,754] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:32:52,756] {logging_mixin.py:109} INFO - [2022-11-18 11:32:52,756] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:32:53,043] {logging_mixin.py:109} INFO - [2022-11-18 11:32:53,041] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 11:32:53,071] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:32:53,085] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.342 seconds
[2022-11-18 11:33:55,207] {processor.py:163} INFO - Started process (PID=1086) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:33:55,249] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:33:55,258] {logging_mixin.py:109} INFO - [2022-11-18 11:33:55,258] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:34:00,621] {logging_mixin.py:109} INFO - [2022-11-18 11:34:00,556] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 11:34:01,251] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 11:34:01,789] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 6.677 seconds
[2022-11-18 11:39:21,391] {processor.py:163} INFO - Started process (PID=1223) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:39:22,079] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:39:22,523] {logging_mixin.py:109} INFO - [2022-11-18 11:39:22,239] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:40:03,487] {logging_mixin.py:109} INFO - [2022-11-18 11:40:03,486] {timeout.py:36} ERROR - Process timed out, PID: 1223
[2022-11-18 11:40:14,833] {logging_mixin.py:109} INFO - [2022-11-18 11:40:11,157] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.cpython-37m-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 2, in <module>
    from airflow.operators.python import PythonOperator
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/manager.py", line 496, in _exit_gracefully
    self.log.debug("Current Stacktrace is: %s", '\n'.join(map(str, inspect.stack())))
  File "/usr/local/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/local/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/local/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/local/lib/python3.7/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/usr/local/lib/python3.7/inspect.py", line 739, in getmodule
    f = getabsfile(module)
  File "/usr/local/lib/python3.7/inspect.py", line 708, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/local/lib/python3.7/inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "/usr/local/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/validator.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.4/best-practices.html#reducing-dag-complexity, PID: 1223
[2022-11-18 11:50:38,172] {processor.py:163} INFO - Started process (PID=1336) to work on /opt/airflow/dags/validator.py
[2022-11-18 11:50:40,469] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 11:50:42,681] {logging_mixin.py:109} INFO - [2022-11-18 11:50:41,805] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 11:51:19,647] {logging_mixin.py:109} INFO - [2022-11-18 11:51:17,045] {timeout.py:36} ERROR - Process timed out, PID: 1336
[2022-11-18 12:06:53,867] {processor.py:163} INFO - Started process (PID=62) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:06:53,910] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:06:53,912] {logging_mixin.py:109} INFO - [2022-11-18 12:06:53,911] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:06:55,795] {logging_mixin.py:109} INFO - [2022-11-18 12:06:55,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:06:55,875] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:06:55,928] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 2.100 seconds
[2022-11-18 12:07:30,604] {processor.py:163} INFO - Started process (PID=108) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:07:30,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:07:30,632] {logging_mixin.py:109} INFO - [2022-11-18 12:07:30,632] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:07:33,180] {logging_mixin.py:109} INFO - [2022-11-18 12:07:33,158] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:07:33,400] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:07:33,573] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 2.984 seconds
[2022-11-18 12:08:04,476] {processor.py:163} INFO - Started process (PID=162) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:08:04,487] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:08:04,488] {logging_mixin.py:109} INFO - [2022-11-18 12:08:04,488] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:08:04,666] {logging_mixin.py:109} INFO - [2022-11-18 12:08:04,665] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:08:04,688] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:08:04,699] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.228 seconds
[2022-11-18 12:08:34,923] {processor.py:163} INFO - Started process (PID=215) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:08:34,926] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:08:34,929] {logging_mixin.py:109} INFO - [2022-11-18 12:08:34,929] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:08:35,102] {logging_mixin.py:109} INFO - [2022-11-18 12:08:35,100] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:08:35,125] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:08:35,142] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.229 seconds
[2022-11-18 12:09:05,227] {processor.py:163} INFO - Started process (PID=268) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:09:05,234] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:09:05,236] {logging_mixin.py:109} INFO - [2022-11-18 12:09:05,236] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:09:05,478] {logging_mixin.py:109} INFO - [2022-11-18 12:09:05,475] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:09:05,519] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:09:05,533] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.319 seconds
[2022-11-18 12:09:35,808] {processor.py:163} INFO - Started process (PID=321) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:09:35,815] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:09:35,824] {logging_mixin.py:109} INFO - [2022-11-18 12:09:35,820] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:09:36,174] {logging_mixin.py:109} INFO - [2022-11-18 12:09:36,172] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:09:36,271] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:09:36,295] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.502 seconds
[2022-11-18 12:10:06,512] {processor.py:163} INFO - Started process (PID=373) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:10:06,518] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:10:06,520] {logging_mixin.py:109} INFO - [2022-11-18 12:10:06,519] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:10:06,858] {logging_mixin.py:109} INFO - [2022-11-18 12:10:06,857] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/validator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/validator.py", line 114, in <module>
    python_callable=validate_file,
NameError: name 'validate_file' is not defined
[2022-11-18 12:10:06,881] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:10:06,894] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.397 seconds
[2022-11-18 12:10:34,231] {processor.py:163} INFO - Started process (PID=413) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:10:34,285] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:10:34,290] {logging_mixin.py:109} INFO - [2022-11-18 12:10:34,289] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:10:35,424] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:10:44,111] {logging_mixin.py:109} INFO - [2022-11-18 12:10:44,111] {manager.py:496} INFO - Created Permission View: can edit on DAG:validator
[2022-11-18 12:10:44,127] {logging_mixin.py:109} INFO - [2022-11-18 12:10:44,127] {manager.py:496} INFO - Created Permission View: can read on DAG:validator
[2022-11-18 12:10:44,128] {logging_mixin.py:109} INFO - [2022-11-18 12:10:44,127] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:10:44,139] {logging_mixin.py:109} INFO - [2022-11-18 12:10:44,139] {dag.py:2417} INFO - Creating ORM DAG for validator
[2022-11-18 12:10:44,151] {logging_mixin.py:109} INFO - [2022-11-18 12:10:44,151] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:10:44,168] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 9.956 seconds
[2022-11-18 12:11:14,861] {processor.py:163} INFO - Started process (PID=486) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:11:14,862] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:11:14,864] {logging_mixin.py:109} INFO - [2022-11-18 12:11:14,863] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:11:15,043] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:11:15,076] {logging_mixin.py:109} INFO - [2022-11-18 12:11:15,076] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:11:15,113] {logging_mixin.py:109} INFO - [2022-11-18 12:11:15,112] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:11:15,123] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.266 seconds
[2022-11-18 12:11:45,782] {processor.py:163} INFO - Started process (PID=530) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:11:45,784] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:11:45,785] {logging_mixin.py:109} INFO - [2022-11-18 12:11:45,785] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:11:45,926] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:11:45,937] {logging_mixin.py:109} INFO - [2022-11-18 12:11:45,937] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:11:45,954] {logging_mixin.py:109} INFO - [2022-11-18 12:11:45,954] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:11:45,964] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.189 seconds
[2022-11-18 12:12:16,103] {processor.py:163} INFO - Started process (PID=592) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:12:16,105] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:12:16,106] {logging_mixin.py:109} INFO - [2022-11-18 12:12:16,106] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:12:16,229] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:12:16,239] {logging_mixin.py:109} INFO - [2022-11-18 12:12:16,239] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:12:16,254] {logging_mixin.py:109} INFO - [2022-11-18 12:12:16,253] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:12:16,263] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.166 seconds
[2022-11-18 12:12:46,313] {processor.py:163} INFO - Started process (PID=645) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:12:46,317] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:12:46,319] {logging_mixin.py:109} INFO - [2022-11-18 12:12:46,319] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:12:46,445] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:12:46,454] {logging_mixin.py:109} INFO - [2022-11-18 12:12:46,454] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:12:46,468] {logging_mixin.py:109} INFO - [2022-11-18 12:12:46,468] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:12:46,478] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.177 seconds
[2022-11-18 12:13:16,880] {processor.py:163} INFO - Started process (PID=699) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:13:16,882] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:13:16,884] {logging_mixin.py:109} INFO - [2022-11-18 12:13:16,883] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:13:17,080] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:13:17,094] {logging_mixin.py:109} INFO - [2022-11-18 12:13:17,094] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:13:17,121] {logging_mixin.py:109} INFO - [2022-11-18 12:13:17,121] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:13:17,136] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.260 seconds
[2022-11-18 12:13:47,200] {processor.py:163} INFO - Started process (PID=761) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:13:47,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:13:47,202] {logging_mixin.py:109} INFO - [2022-11-18 12:13:47,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:13:47,341] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:13:47,350] {logging_mixin.py:109} INFO - [2022-11-18 12:13:47,350] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:13:47,366] {logging_mixin.py:109} INFO - [2022-11-18 12:13:47,366] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:13:47,376] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.180 seconds
[2022-11-18 12:14:17,594] {processor.py:163} INFO - Started process (PID=814) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:14:17,596] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:14:17,597] {logging_mixin.py:109} INFO - [2022-11-18 12:14:17,597] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:14:17,729] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:14:17,740] {logging_mixin.py:109} INFO - [2022-11-18 12:14:17,740] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:14:17,757] {logging_mixin.py:109} INFO - [2022-11-18 12:14:17,757] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:14:17,767] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.177 seconds
[2022-11-18 12:14:47,920] {processor.py:163} INFO - Started process (PID=867) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:14:47,925] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:14:47,927] {logging_mixin.py:109} INFO - [2022-11-18 12:14:47,926] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:14:48,053] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:14:48,063] {logging_mixin.py:109} INFO - [2022-11-18 12:14:48,062] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:14:48,077] {logging_mixin.py:109} INFO - [2022-11-18 12:14:48,077] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:14:48,087] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.177 seconds
[2022-11-18 12:15:18,189] {processor.py:163} INFO - Started process (PID=921) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:15:18,191] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:15:18,192] {logging_mixin.py:109} INFO - [2022-11-18 12:15:18,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:15:18,339] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:15:18,353] {logging_mixin.py:109} INFO - [2022-11-18 12:15:18,353] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:15:18,380] {logging_mixin.py:109} INFO - [2022-11-18 12:15:18,380] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:15:18,400] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.215 seconds
[2022-11-18 12:15:48,452] {processor.py:163} INFO - Started process (PID=983) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:15:48,463] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:15:48,471] {logging_mixin.py:109} INFO - [2022-11-18 12:15:48,471] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:15:48,686] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:15:48,703] {logging_mixin.py:109} INFO - [2022-11-18 12:15:48,703] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:15:48,729] {logging_mixin.py:109} INFO - [2022-11-18 12:15:48,729] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:15:48,760] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.314 seconds
[2022-11-18 12:16:19,486] {processor.py:163} INFO - Started process (PID=1036) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:16:19,494] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:16:19,499] {logging_mixin.py:109} INFO - [2022-11-18 12:16:19,499] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:16:20,081] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:16:20,113] {logging_mixin.py:109} INFO - [2022-11-18 12:16:20,112] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:16:20,262] {logging_mixin.py:109} INFO - [2022-11-18 12:16:20,261] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:16:20,309] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.874 seconds
[2022-11-18 12:16:50,588] {processor.py:163} INFO - Started process (PID=1089) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:16:50,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:16:50,593] {logging_mixin.py:109} INFO - [2022-11-18 12:16:50,592] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:16:50,723] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:16:50,734] {logging_mixin.py:109} INFO - [2022-11-18 12:16:50,733] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:16:50,749] {logging_mixin.py:109} INFO - [2022-11-18 12:16:50,749] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:16:50,760] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.184 seconds
[2022-11-18 12:17:21,329] {processor.py:163} INFO - Started process (PID=1142) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:17:21,335] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:17:21,339] {logging_mixin.py:109} INFO - [2022-11-18 12:17:21,339] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:17:21,681] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:17:21,699] {logging_mixin.py:109} INFO - [2022-11-18 12:17:21,699] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:17:21,722] {logging_mixin.py:109} INFO - [2022-11-18 12:17:21,721] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:17:21,740] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.429 seconds
[2022-11-18 12:17:51,989] {processor.py:163} INFO - Started process (PID=1196) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:17:51,991] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:17:51,992] {logging_mixin.py:109} INFO - [2022-11-18 12:17:51,992] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:17:52,175] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:17:52,188] {logging_mixin.py:109} INFO - [2022-11-18 12:17:52,188] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:17:52,210] {logging_mixin.py:109} INFO - [2022-11-18 12:17:52,209] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:17:52,219] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.234 seconds
[2022-11-18 12:18:22,361] {processor.py:163} INFO - Started process (PID=1250) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:18:22,364] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:18:22,366] {logging_mixin.py:109} INFO - [2022-11-18 12:18:22,366] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:18:22,635] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:18:22,656] {logging_mixin.py:109} INFO - [2022-11-18 12:18:22,656] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:18:22,685] {logging_mixin.py:109} INFO - [2022-11-18 12:18:22,685] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:18:22,703] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.349 seconds
[2022-11-18 12:18:52,842] {processor.py:163} INFO - Started process (PID=1304) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:18:52,844] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:18:52,847] {logging_mixin.py:109} INFO - [2022-11-18 12:18:52,846] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:18:53,193] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:18:53,207] {logging_mixin.py:109} INFO - [2022-11-18 12:18:53,207] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:18:53,240] {logging_mixin.py:109} INFO - [2022-11-18 12:18:53,240] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:18:53,255] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.422 seconds
[2022-11-18 12:19:23,309] {processor.py:163} INFO - Started process (PID=1368) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:19:23,311] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:19:23,312] {logging_mixin.py:109} INFO - [2022-11-18 12:19:23,311] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:19:23,588] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:19:23,603] {logging_mixin.py:109} INFO - [2022-11-18 12:19:23,603] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:19:23,637] {logging_mixin.py:109} INFO - [2022-11-18 12:19:23,637] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:19:23,664] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.360 seconds
[2022-11-18 12:19:54,457] {processor.py:163} INFO - Started process (PID=1421) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:19:54,458] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:19:54,459] {logging_mixin.py:109} INFO - [2022-11-18 12:19:54,459] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:19:54,660] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:19:54,672] {logging_mixin.py:109} INFO - [2022-11-18 12:19:54,672] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:19:54,690] {logging_mixin.py:109} INFO - [2022-11-18 12:19:54,690] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:19:54,699] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.246 seconds
[2022-11-18 12:20:25,677] {processor.py:163} INFO - Started process (PID=1474) to work on /opt/airflow/dags/validator.py
[2022-11-18 12:20:25,683] {processor.py:642} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18 12:20:25,687] {logging_mixin.py:109} INFO - [2022-11-18 12:20:25,687] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18 12:20:25,876] {processor.py:654} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18 12:20:25,884] {logging_mixin.py:109} INFO - [2022-11-18 12:20:25,884] {dag.py:2398} INFO - Sync 1 DAGs
[2022-11-18 12:20:25,900] {logging_mixin.py:109} INFO - [2022-11-18 12:20:25,900] {dag.py:2937} INFO - Setting next_dagrun for validator to None
[2022-11-18 12:20:25,909] {processor.py:171} INFO - Processing /opt/airflow/dags/validator.py took 0.243 seconds
[2022-11-18T12:28:52.242+0000] {processor.py:154} INFO - Started process (PID=51) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:28:52.252+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:28:52.260+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:52.260+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:28:53.849+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:28:54.611+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:54.611+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:validator
[2022-11-18T12:28:54.648+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:54.648+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:validator
[2022-11-18T12:28:54.683+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:54.683+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:validator
[2022-11-18T12:28:54.687+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:54.687+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:28:54.749+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:54.745+0000] {dag.py:2606} INFO - Creating ORM DAG for validator
[2022-11-18T12:28:54.790+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:54.790+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:28:54.855+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 2.642 seconds
[2022-11-18T12:29:24.956+0000] {processor.py:154} INFO - Started process (PID=108) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:29:24.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:29:24.959+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:24.958+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:29:25.097+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:29:25.142+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:25.142+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:29:25.198+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:25.198+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:29:25.243+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.294 seconds
[2022-11-18T12:29:55.706+0000] {processor.py:154} INFO - Started process (PID=164) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:29:55.807+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:29:55.895+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:55.894+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:29:59.181+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:29:59.514+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:59.514+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:30:00.008+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:30:00.007+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:30:00.252+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 4.638 seconds
[2022-11-18T12:30:31.090+0000] {processor.py:154} INFO - Started process (PID=222) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:30:31.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:30:31.097+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:30:31.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:30:31.613+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:30:31.663+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:30:31.663+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:30:31.707+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:30:31.707+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:30:31.737+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.654 seconds
[2022-11-18T12:31:02.067+0000] {processor.py:154} INFO - Started process (PID=278) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:31:02.072+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:31:02.076+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:02.075+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:31:02.485+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:31:02.518+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:02.518+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:31:02.551+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:02.551+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:31:02.594+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.535 seconds
[2022-11-18T12:31:33.094+0000] {processor.py:154} INFO - Started process (PID=335) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:31:33.100+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:31:33.104+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:33.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:31:33.379+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:31:33.415+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:33.414+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:31:33.446+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:33.446+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:31:33.469+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.392 seconds
[2022-11-18T12:32:12.795+0000] {processor.py:154} INFO - Started process (PID=380) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:32:12.851+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:32:12.874+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:32:12.862+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:32:20.376+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:32:21.791+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:32:21.780+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:32:22.677+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:32:22.676+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:32:23.433+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 11.018 seconds
[2022-11-18T12:33:00.582+0000] {processor.py:154} INFO - Started process (PID=446) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:33:00.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:33:00.585+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:00.585+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:33:01.109+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:33:01.214+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:01.214+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:33:01.261+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:01.261+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:33:01.295+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 0.727 seconds
[2022-11-18T12:33:49.246+0000] {processor.py:154} INFO - Started process (PID=499) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:33:49.329+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:33:49.351+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:49.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:34:01.854+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:34:04.674+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:04.630+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:34:06.203+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:06.196+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:34:07.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 18.077 seconds
[2022-11-18T12:34:44.664+0000] {processor.py:154} INFO - Started process (PID=537) to work on /opt/airflow/dags/validator.py
[2022-11-18T12:34:44.751+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/validator.py for tasks to queue
[2022-11-18T12:34:44.766+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:44.765+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/validator.py
[2022-11-18T12:34:49.653+0000] {processor.py:766} INFO - DAG(s) dict_keys(['validator']) retrieved from /opt/airflow/dags/validator.py
[2022-11-18T12:34:50.070+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:50.069+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-18T12:34:50.583+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:50.576+0000] {dag.py:3340} INFO - Setting next_dagrun for validator to None, run_after=None
[2022-11-18T12:34:51.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/validator.py took 6.565 seconds
